/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface ConversationView {
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
}
export interface Event {
  'date' : Time,
  'name' : string,
  'description' : string,
  'location' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Lesson {
  'media' : [] | [ExternalBlob],
  'title' : string,
  'content' : string,
}
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export type PostMediaType = { 'video' : null } |
  { 'image' : null };
export interface PostView {
  'id' : string,
  'media' : [] | [ExternalBlob],
  'isEvent' : boolean,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
  'caption' : string,
  'mediaType' : PostMediaType,
  'comments' : Array<Comment>,
  'eventName' : [] | [string],
}
export interface PublicProfile {
  'bio' : string,
  'userType' : UserType,
  'verified' : boolean,
  'musicianTag' : [] | [boolean],
  'displayName' : string,
  'influencerTag' : [] | [boolean],
  'painterTag' : [] | [boolean],
  'teacherBadge' : boolean,
  'singerTag' : [] | [boolean],
  'location' : [] | [string],
  'dancerTag' : [] | [boolean],
  'avatar' : [] | [ExternalBlob],
}
export interface Story {
  'id' : string,
  'content' : ExternalBlob,
  'author' : Principal,
  'timestamp' : Time,
  'mediaType' : PostMediaType,
}
export interface StoryView { 'story' : Story, 'authorProfile' : PublicProfile }
export interface StudyView {
  'id' : string,
  'participants' : Array<Principal>,
  'instructor' : Principal,
  'name' : string,
  'materials' : Array<[string, ExternalBlob]>,
  'schedule' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'publicProfile' : PublicProfile,
  'countryCode' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSearchResult { 'displayName' : string, 'userId' : string }
export type UserType = { 'creator' : null } |
  { 'user' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'addEvent' : ActorMethod<[string, Time, string, [] | [string]], undefined>,
  'addLesson' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'addMaterial' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'addToChannel' : ActorMethod<[string, string], undefined>,
  'adminAddEvent' : ActorMethod<
    [string, Time, string, [] | [string]],
    undefined
  >,
  'adminBanUser' : ActorMethod<[Principal], undefined>,
  'adminGetConversation' : ActorMethod<
    [Principal, Principal],
    [] | [ConversationView]
  >,
  'adminGetConversationList' : ActorMethod<[Principal], Array<Principal>>,
  'adminGrantTeacherBadge' : ActorMethod<[Principal], undefined>,
  'adminIsUserBanned' : ActorMethod<[Principal], boolean>,
  'adminRevokeTeacherBadge' : ActorMethod<[Principal], undefined>,
  'adminSetVerified' : ActorMethod<[Principal, boolean], undefined>,
  'adminUnbanUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkRole' : ActorMethod<[Principal], [] | [UserRole]>,
  'createEventPost' : ActorMethod<
    [string, string, [] | [ExternalBlob], PostMediaType],
    string
  >,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], PostMediaType],
    string
  >,
  'createStory' : ActorMethod<[ExternalBlob, PostMediaType], string>,
  'createStudy' : ActorMethod<
    [string, Array<[string, ExternalBlob]>, string, Principal],
    string
  >,
  'expireStories' : ActorMethod<[], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllLessons' : ActorMethod<[], Array<Lesson>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelPosts' : ActorMethod<[string], Array<PostView>>,
  'getConversation' : ActorMethod<[Principal], [] | [ConversationView]>,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getFeedStories' : ActorMethod<[], Array<Story>>,
  'getFeedStoryViews' : ActorMethod<[], Array<StoryView>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getLesson' : ActorMethod<[string], [] | [Lesson]>,
  'getPosts' : ActorMethod<[], Array<PostView>>,
  'getStudy' : ActorMethod<[string], [] | [StudyView]>,
  'getStudyIds' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPublicProfile' : ActorMethod<[Principal], [] | [PublicProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'joinStudy' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsersByDisplayName' : ActorMethod<[string], Array<UserSearchResult>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'updateAvatar' : ActorMethod<[[] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];