/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostMediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const Event = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});
export const Lesson = IDL.Record({
  'media' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const UserType = IDL.Variant({
  'creator' : IDL.Null,
  'user' : IDL.Null,
});
export const PublicProfile = IDL.Record({
  'bio' : IDL.Text,
  'userType' : UserType,
  'verified' : IDL.Bool,
  'musicianTag' : IDL.Opt(IDL.Bool),
  'displayName' : IDL.Text,
  'influencerTag' : IDL.Opt(IDL.Bool),
  'painterTag' : IDL.Opt(IDL.Bool),
  'teacherBadge' : IDL.Bool,
  'singerTag' : IDL.Opt(IDL.Bool),
  'location' : IDL.Opt(IDL.Text),
  'dancerTag' : IDL.Opt(IDL.Bool),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'publicProfile' : PublicProfile,
  'countryCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Opt(ExternalBlob),
  'isEvent' : IDL.Bool,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'caption' : IDL.Text,
  'mediaType' : PostMediaType,
  'comments' : IDL.Vec(Comment),
  'eventName' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const ConversationView = IDL.Record({
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
});
export const Story = IDL.Record({
  'id' : IDL.Text,
  'content' : ExternalBlob,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'mediaType' : PostMediaType,
});
export const StoryView = IDL.Record({
  'story' : Story,
  'authorProfile' : PublicProfile,
});
export const StudyView = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'instructor' : IDL.Principal,
  'name' : IDL.Text,
  'materials' : IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
  'schedule' : IDL.Opt(IDL.Text),
});
export const UserSearchResult = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addEvent' : IDL.Func([IDL.Text, Time, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addLesson' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'addMaterial' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'addToChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminAddEvent' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'adminApplyVerified' : IDL.Func([IDL.Principal], [], []),
  'adminBanUser' : IDL.Func([IDL.Principal], [], []),
  'adminGrantTeacherBadge' : IDL.Func([IDL.Principal], [], []),
  'adminIsUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'adminRevokeTeacherBadge' : IDL.Func([IDL.Principal], [], []),
  'adminUnbanUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
  'createEventPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), PostMediaType],
      [IDL.Text],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), PostMediaType],
      [IDL.Text],
      [],
    ),
  'createStory' : IDL.Func([ExternalBlob, PostMediaType], [IDL.Text], []),
  'createStudy' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
        IDL.Text,
        IDL.Principal,
      ],
      [IDL.Text],
      [],
    ),
  'expireStories' : IDL.Func([], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ConversationView)],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getFeedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getFeedStoryViews' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getLesson' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getStudy' : IDL.Func([IDL.Text], [IDL.Opt(StudyView)], ['query']),
  'getStudyIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'joinStudy' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsersByDisplayName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserSearchResult)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'updateAvatar' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostMediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const Event = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  const Lesson = IDL.Record({
    'media' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const UserType = IDL.Variant({ 'creator' : IDL.Null, 'user' : IDL.Null });
  const PublicProfile = IDL.Record({
    'bio' : IDL.Text,
    'userType' : UserType,
    'verified' : IDL.Bool,
    'musicianTag' : IDL.Opt(IDL.Bool),
    'displayName' : IDL.Text,
    'influencerTag' : IDL.Opt(IDL.Bool),
    'painterTag' : IDL.Opt(IDL.Bool),
    'teacherBadge' : IDL.Bool,
    'singerTag' : IDL.Opt(IDL.Bool),
    'location' : IDL.Opt(IDL.Text),
    'dancerTag' : IDL.Opt(IDL.Bool),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'publicProfile' : PublicProfile,
    'countryCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Opt(ExternalBlob),
    'isEvent' : IDL.Bool,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'caption' : IDL.Text,
    'mediaType' : PostMediaType,
    'comments' : IDL.Vec(Comment),
    'eventName' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const ConversationView = IDL.Record({
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
  });
  const Story = IDL.Record({
    'id' : IDL.Text,
    'content' : ExternalBlob,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'mediaType' : PostMediaType,
  });
  const StoryView = IDL.Record({
    'story' : Story,
    'authorProfile' : PublicProfile,
  });
  const StudyView = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'instructor' : IDL.Principal,
    'name' : IDL.Text,
    'materials' : IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
    'schedule' : IDL.Opt(IDL.Text),
  });
  const UserSearchResult = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addEvent' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addLesson' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'addMaterial' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'addToChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminAddEvent' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminApplyVerified' : IDL.Func([IDL.Principal], [], []),
    'adminBanUser' : IDL.Func([IDL.Principal], [], []),
    'adminGrantTeacherBadge' : IDL.Func([IDL.Principal], [], []),
    'adminIsUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'adminRevokeTeacherBadge' : IDL.Func([IDL.Principal], [], []),
    'adminUnbanUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
    'createEventPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), PostMediaType],
        [IDL.Text],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), PostMediaType],
        [IDL.Text],
        [],
      ),
    'createStory' : IDL.Func([ExternalBlob, PostMediaType], [IDL.Text], []),
    'createStudy' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
          IDL.Text,
          IDL.Principal,
        ],
        [IDL.Text],
        [],
      ),
    'expireStories' : IDL.Func([], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ConversationView)],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getFeedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getFeedStoryViews' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getLesson' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getStudy' : IDL.Func([IDL.Text], [IDL.Opt(StudyView)], ['query']),
    'getStudyIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'joinStudy' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsersByDisplayName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserSearchResult)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'updateAvatar' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };