/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudyView {
    id: string;
    participants: Array<Principal>;
    instructor: Principal;
    name: string;
    materials: Array<[string, ExternalBlob]>;
    schedule?: string;
}
export type Time = bigint;
export interface Comment {
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Story {
    id: string;
    content: ExternalBlob;
    author: Principal;
    timestamp: Time;
    mediaType: PostMediaType;
}
export interface PostView {
    id: string;
    media?: ExternalBlob;
    isEvent: boolean;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
    caption: string;
    mediaType: PostMediaType;
    comments: Array<Comment>;
    eventName?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Event {
    date: Time;
    name: string;
    description: string;
    location?: string;
}
export interface UserSearchResult {
    displayName: string;
    userId: string;
}
export interface ConversationView {
    participants: Array<Principal>;
    messages: Array<Message>;
}
export interface PublicProfile {
    bio: string;
    userType: UserType;
    verified: boolean;
    musicianTag?: boolean;
    displayName: string;
    influencerTag?: boolean;
    painterTag?: boolean;
    teacherBadge: boolean;
    singerTag?: boolean;
    location?: string;
    dancerTag?: boolean;
    avatar?: ExternalBlob;
}
export interface Lesson {
    media?: ExternalBlob;
    title: string;
    content: string;
}
export interface StoryView {
    story: Story;
    authorProfile: PublicProfile;
}
export interface Message {
    content: string;
    sender: Principal;
    timestamp: Time;
}
export interface UserProfile {
    publicProfile: PublicProfile;
    countryCode: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PostMediaType {
    video = "video",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    creator = "creator",
    user = "user"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(postId: string, content: string): Promise<void>;
    addEvent(name: string, date: Time, description: string, location: string | null): Promise<void>;
    addLesson(title: string, content: string, media: ExternalBlob | null): Promise<void>;
    addMaterial(studyId: string, materialId: string, material: ExternalBlob): Promise<void>;
    addToChannel(channelName: string, postId: string): Promise<void>;
    adminAddEvent(name: string, date: Time, description: string, location: string | null): Promise<void>;
    adminBanUser(user: Principal): Promise<void>;
    adminGetConversation(_adminTargetUser: Principal, otherUser: Principal): Promise<ConversationView | null>;
    adminGetConversationList(targetUser: Principal): Promise<Array<Principal>>;
    adminGrantTeacherBadge(user: Principal): Promise<void>;
    adminIsUserBanned(user: Principal): Promise<boolean>;
    adminRevokeTeacherBadge(user: Principal): Promise<void>;
    adminSetVerified(user: Principal, verified: boolean): Promise<void>;
    adminUnbanUser(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkRole(target: Principal): Promise<UserRole | null>;
    createEventPost(eventName: string, caption: string, media: ExternalBlob | null, mediaType: PostMediaType): Promise<string>;
    createPost(caption: string, media: ExternalBlob | null, mediaType: PostMediaType): Promise<string>;
    createStory(content: ExternalBlob, mediaType: PostMediaType): Promise<string>;
    createStudy(name: string, materials: Array<[string, ExternalBlob]>, schedule: string, instructor: Principal): Promise<string>;
    expireStories(): Promise<void>;
    followUser(target: Principal): Promise<void>;
    getAllEvents(): Promise<Array<Event>>;
    getAllLessons(): Promise<Array<Lesson>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannelPosts(channelName: string): Promise<Array<PostView>>;
    getConversation(otherUser: Principal): Promise<ConversationView | null>;
    getEvent(name: string): Promise<Event | null>;
    getFeedStories(): Promise<Array<Story>>;
    getFeedStoryViews(): Promise<Array<StoryView>>;
    getFollowers(target: Principal): Promise<Array<Principal>>;
    getFollowing(target: Principal): Promise<Array<Principal>>;
    getLesson(title: string): Promise<Lesson | null>;
    getPosts(): Promise<Array<PostView>>;
    getStudy(studyId: string): Promise<StudyView | null>;
    getStudyIds(): Promise<Array<string>>;
    getUserProfile(target: Principal): Promise<UserProfile | null>;
    getUserPublicProfile(target: Principal): Promise<PublicProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(target: Principal): Promise<boolean>;
    joinStudy(studyId: string): Promise<void>;
    likePost(postId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchUsersByDisplayName(search: string): Promise<Array<UserSearchResult>>;
    sendMessage(receiver: Principal, content: string): Promise<void>;
    unfollowUser(target: Principal): Promise<void>;
    unlikePost(postId: string): Promise<void>;
    updateAvatar(newAvatar: ExternalBlob | null): Promise<void>;
}
import type { Comment as _Comment, ConversationView as _ConversationView, Event as _Event, ExternalBlob as _ExternalBlob, Lesson as _Lesson, PostMediaType as _PostMediaType, PostView as _PostView, PublicProfile as _PublicProfile, Story as _Story, StoryView as _StoryView, StudyView as _StudyView, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addEvent(arg0: string, arg1: Time, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addLesson(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLesson(arg0, arg1, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLesson(arg0, arg1, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addMaterial(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaterial(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaterial(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addToChannel(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToChannel(arg0, arg1);
            return result;
        }
    }
    async adminAddEvent(arg0: string, arg1: Time, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddEvent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddEvent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async adminBanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBanUser(arg0);
            return result;
        }
    }
    async adminGetConversation(arg0: Principal, arg1: Principal): Promise<ConversationView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetConversation(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetConversation(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetConversationList(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetConversationList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetConversationList(arg0);
            return result;
        }
    }
    async adminGrantTeacherBadge(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGrantTeacherBadge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGrantTeacherBadge(arg0);
            return result;
        }
    }
    async adminIsUserBanned(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminIsUserBanned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminIsUserBanned(arg0);
            return result;
        }
    }
    async adminRevokeTeacherBadge(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRevokeTeacherBadge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRevokeTeacherBadge(arg0);
            return result;
        }
    }
    async adminSetVerified(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetVerified(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetVerified(arg0, arg1);
            return result;
        }
    }
    async adminUnbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnbanUser(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkRole(arg0: Principal): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkRole(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkRole(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEventPost(arg0: string, arg1: string, arg2: ExternalBlob | null, arg3: PostMediaType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEventPost(arg0, arg1, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), to_candid_PostMediaType_n17(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEventPost(arg0, arg1, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), to_candid_PostMediaType_n17(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createPost(arg0: string, arg1: ExternalBlob | null, arg2: PostMediaType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_PostMediaType_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_PostMediaType_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createStory(arg0: ExternalBlob, arg1: PostMediaType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0), to_candid_PostMediaType_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0), to_candid_PostMediaType_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createStudy(arg0: string, arg1: Array<[string, ExternalBlob]>, arg2: string, arg3: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudy(arg0, await to_candid_vec_n19(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudy(arg0, await to_candid_vec_n19(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async expireStories(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.expireStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.expireStories();
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLessons();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLessons();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelPosts(arg0: string): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelPosts(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelPosts(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<ConversationView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedStories();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedStories();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedStoryViews(): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedStoryViews();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedStoryViews();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getLesson(arg0: string): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudy(arg0: string): Promise<StudyView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudy(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudy(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyIds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyIds();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPublicProfile(arg0: Principal): Promise<PublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPublicProfile(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPublicProfile(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async joinStudy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinStudy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinStudy(arg0);
            return result;
        }
    }
    async likePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchUsersByDisplayName(arg0: string): Promise<Array<UserSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByDisplayName(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async updateAvatar(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatar(await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatar(await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Event_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Lesson_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Promise<Lesson> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PostMediaType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostMediaType): PostMediaType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_PostView_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostView): Promise<PostView> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfile): Promise<PublicProfile> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_StoryView_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryView): Promise<StoryView> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_Story_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Promise<Story> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_StudyView_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyView): Promise<StudyView> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConversationView]): ConversationView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lesson]): Promise<Lesson | null> {
    return value.length === 0 ? null : await from_candid_Lesson_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyView]): Promise<StudyView | null> {
    return value.length === 0 ? null : await from_candid_StudyView_n51(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfile]): Promise<PublicProfile | null> {
    return value.length === 0 ? null : await from_candid_PublicProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    name: string;
    description: string;
    location: [] | [string];
}): {
    date: Time;
    name: string;
    description: string;
    location?: string;
} {
    return {
        date: value.date,
        name: value.name,
        description: value.description,
        location: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.location))
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media: [] | [_ExternalBlob];
    title: string;
    content: string;
}): Promise<{
    media?: ExternalBlob;
    title: string;
    content: string;
}> {
    return {
        media: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.media)),
        title: value.title,
        content: value.content
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicProfile: _PublicProfile;
    countryCode: string;
    phone: string;
}): Promise<{
    publicProfile: PublicProfile;
    countryCode: string;
    phone: string;
}> {
    return {
        publicProfile: await from_candid_PublicProfile_n33(_uploadFile, _downloadFile, value.publicProfile),
        countryCode: value.countryCode,
        phone: value.phone
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    userType: _UserType;
    verified: boolean;
    musicianTag: [] | [boolean];
    displayName: string;
    influencerTag: [] | [boolean];
    painterTag: [] | [boolean];
    teacherBadge: boolean;
    singerTag: [] | [boolean];
    location: [] | [string];
    dancerTag: [] | [boolean];
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    userType: UserType;
    verified: boolean;
    musicianTag?: boolean;
    displayName: string;
    influencerTag?: boolean;
    painterTag?: boolean;
    teacherBadge: boolean;
    singerTag?: boolean;
    location?: string;
    dancerTag?: boolean;
    avatar?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        userType: from_candid_UserType_n35(_uploadFile, _downloadFile, value.userType),
        verified: value.verified,
        musicianTag: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.musicianTag)),
        displayName: value.displayName,
        influencerTag: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.influencerTag)),
        painterTag: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.painterTag)),
        teacherBadge: value.teacherBadge,
        singerTag: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.singerTag)),
        location: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.location)),
        dancerTag: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.dancerTag)),
        avatar: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: [] | [_ExternalBlob];
    isEvent: boolean;
    author: Principal;
    likes: Array<Principal>;
    timestamp: _Time;
    caption: string;
    mediaType: _PostMediaType;
    comments: Array<_Comment>;
    eventName: [] | [string];
}): Promise<{
    id: string;
    media?: ExternalBlob;
    isEvent: boolean;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
    caption: string;
    mediaType: PostMediaType;
    comments: Array<Comment>;
    eventName?: string;
}> {
    return {
        id: value.id,
        media: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.media)),
        isEvent: value.isEvent,
        author: value.author,
        likes: value.likes,
        timestamp: value.timestamp,
        caption: value.caption,
        mediaType: from_candid_PostMediaType_n40(_uploadFile, _downloadFile, value.mediaType),
        comments: value.comments,
        eventName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.eventName))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: _ExternalBlob;
    author: Principal;
    timestamp: _Time;
    mediaType: _PostMediaType;
}): Promise<{
    id: string;
    content: ExternalBlob;
    author: Principal;
    timestamp: Time;
    mediaType: PostMediaType;
}> {
    return {
        id: value.id,
        content: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.content),
        author: value.author,
        timestamp: value.timestamp,
        mediaType: from_candid_PostMediaType_n40(_uploadFile, _downloadFile, value.mediaType)
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    story: _Story;
    authorProfile: _PublicProfile;
}): Promise<{
    story: Story;
    authorProfile: PublicProfile;
}> {
    return {
        story: await from_candid_Story_n44(_uploadFile, _downloadFile, value.story),
        authorProfile: await from_candid_PublicProfile_n33(_uploadFile, _downloadFile, value.authorProfile)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    participants: Array<Principal>;
    instructor: Principal;
    name: string;
    materials: Array<[string, _ExternalBlob]>;
    schedule: [] | [string];
}): Promise<{
    id: string;
    participants: Array<Principal>;
    instructor: Principal;
    name: string;
    materials: Array<[string, ExternalBlob]>;
    schedule?: string;
}> {
    return {
        id: value.id,
        participants: value.participants,
        instructor: value.instructor,
        name: value.name,
        materials: await from_candid_vec_n53(_uploadFile, _downloadFile, value.materials),
        schedule: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.schedule))
    };
}
async function from_candid_tuple_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExternalBlob]): Promise<[string, ExternalBlob]> {
    return [
        value[0],
        await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: null;
} | {
    user: null;
}): UserType {
    return "creator" in value ? UserType.creator : "user" in value ? UserType.user : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): PostMediaType {
    return "video" in value ? PostMediaType.video : "image" in value ? PostMediaType.image : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n22(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Promise<Array<Lesson>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Lesson_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostView>): Promise<Array<PostView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostView_n38(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Promise<Array<Story>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Story_n44(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryView>): Promise<Array<StoryView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StoryView_n47(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExternalBlob]>): Promise<Array<[string, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n54(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PostMediaType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostMediaType): _PostMediaType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_PublicProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicProfile): Promise<_PublicProfile> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicProfile: PublicProfile;
    countryCode: string;
    phone: string;
}): Promise<{
    publicProfile: _PublicProfile;
    countryCode: string;
    phone: string;
}> {
    return {
        publicProfile: await to_candid_PublicProfile_n58(_uploadFile, _downloadFile, value.publicProfile),
        countryCode: value.countryCode,
        phone: value.phone
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    userType: UserType;
    verified: boolean;
    musicianTag?: boolean;
    displayName: string;
    influencerTag?: boolean;
    painterTag?: boolean;
    teacherBadge: boolean;
    singerTag?: boolean;
    location?: string;
    dancerTag?: boolean;
    avatar?: ExternalBlob;
}): Promise<{
    bio: string;
    userType: _UserType;
    verified: boolean;
    musicianTag: [] | [boolean];
    displayName: string;
    influencerTag: [] | [boolean];
    painterTag: [] | [boolean];
    teacherBadge: boolean;
    singerTag: [] | [boolean];
    location: [] | [string];
    dancerTag: [] | [boolean];
    avatar: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        userType: to_candid_UserType_n60(_uploadFile, _downloadFile, value.userType),
        verified: value.verified,
        musicianTag: value.musicianTag ? candid_some(value.musicianTag) : candid_none(),
        displayName: value.displayName,
        influencerTag: value.influencerTag ? candid_some(value.influencerTag) : candid_none(),
        painterTag: value.painterTag ? candid_some(value.painterTag) : candid_none(),
        teacherBadge: value.teacherBadge,
        singerTag: value.singerTag ? candid_some(value.singerTag) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        dancerTag: value.dancerTag ? candid_some(value.dancerTag) : candid_none(),
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
async function to_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, ExternalBlob]): Promise<[string, _ExternalBlob]> {
    return [
        value[0],
        await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostMediaType): {
    video: null;
} | {
    image: null;
} {
    return value == PostMediaType.video ? {
        video: null
    } : value == PostMediaType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    creator: null;
} | {
    user: null;
} {
    return value == UserType.creator ? {
        creator: null
    } : value == UserType.user ? {
        user: null
    } : value;
}
async function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, ExternalBlob]>): Promise<Array<[string, _ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await to_candid_tuple_n20(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
